//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store_Management_System.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseMagasinEntities : DbContext
    {
        public DataBaseMagasinEntities()
            : base("name=DataBaseMagasinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHEF> CHEF { get; set; }
        public virtual DbSet<CHEQUECLIENT> CHEQUECLIENT { get; set; }
        public virtual DbSet<CHEQUEFOURNISSEUR> CHEQUEFOURNISSEUR { get; set; }
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<COMMANDECLIENT> COMMANDECLIENT { get; set; }
        public virtual DbSet<COMMANDEFOUR> COMMANDEFOUR { get; set; }
        public virtual DbSet<COMMANDER> COMMANDER { get; set; }
        public virtual DbSet<EMPLOYE> EMPLOYE { get; set; }
        public virtual DbSet<FOURNISSEUR> FOURNISSEUR { get; set; }
        public virtual DbSet<PAIEMENTESPECECLT> PAIEMENTESPECECLT { get; set; }
        public virtual DbSet<PAIEMENTESPECEFOUR> PAIEMENTESPECEFOUR { get; set; }
        public virtual DbSet<PRODUIT> PRODUIT { get; set; }
        public virtual DbSet<REGLERCHQ> REGLERCHQ { get; set; }
        public virtual DbSet<REGLERESPECE> REGLERESPECE { get; set; }
    }
}
