CREATE Proc [dbo].[CHEQUE_FOURNISSEUR_Encaissement]
(
     @Month  as int ,
	 @Year as int 
)
AS

SELECT  

		MONTH(CHEQUEFOURNISSEUR.DATEPAYER) ,
		CHEQUEFOURNISSEUR.DATEPAYER,
		CHEQUEFOURNISSEUR.N_CHQ,
		CHEQUEFOURNISSEUR.DATEDONNER,
		CHEQUEFOURNISSEUR.MONTANT

		from CHEQUEFOURNISSEUR 
		INNER JOIN FOURNISSEUR ON CHEQUEFOURNISSEUR.IDFOUR = FOURNISSEUR.IDFOUR 
		
		where month(CHEQUEFOURNISSEUR.DATEPAYER) = @Month and year(CHEQUEFOURNISSEUR.DATEPAYER) = @Year

ORDER BY CHEQUEFOURNISSEUR.DATEPAYER ASC

;
GO