SELECT  CHEQUEFOURNISSEUR.DATEPAYER,
		CHEQUEFOURNISSEUR.N_CHQ,
		FOURNISSEUR.ENTREPRISE, 
		CHEQUEFOURNISSEUR.DATEDONNER,
		CHEQUEFOURNISSEUR.MONTANT
		FROM CHEQUEFOURNISSEUR
INNER JOIN FOURNISSEUR ON CHEQUEFOURNISSEUR.IDFOUR = FOURNISSEUR.IDFOUR ;