USE [DataBaseMagasin]
GO

/****** Object:  StoredProcedure [dbo].[CHEQUE_FOURNISSEUR_NCHQ]    Script Date: 22/09/2022 22:22:45 ******/
DROP PROCEDURE [dbo].[CHEQUE_FOURNISSEUR_NCHQ]
GO

/****** Object:  StoredProcedure [dbo].[CHEQUE_FOURNISSEUR_NCHQ]    Script Date: 22/09/2022 22:22:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE Proc [dbo].[CHEQUE_FOURNISSEUR_NCHQ]
(
     @iD VARCHAR(30)
)
AS

SELECT  

		MONTH(CHEQUEFOURNISSEUR.DATEPAYER) ,
		CHEQUEFOURNISSEUR.DATEPAYER,
		CHEQUEFOURNISSEUR.N_CHQ,
		FOURNISSEUR.ENTREPRISE,
		CHEQUEFOURNISSEUR.DATEDONNER,
		CHEQUEFOURNISSEUR.MONTANT

		from CHEQUEFOURNISSEUR 
		INNER JOIN FOURNISSEUR ON CHEQUEFOURNISSEUR.IDFOUR = FOURNISSEUR.IDFOUR 
		
		where CHEQUEFOURNISSEUR.N_CHQ = @iD

ORDER BY CHEQUEFOURNISSEUR.DATEPAYER ASC

;
GO


